networks:
  django_network:
    driver: bridge

services:
  daphne:
    build: ./eduPlatform
    command: daphne -b 0.0.0.0 -p 8000 eduPlatform.asgi:application
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - django_network
    volumes:
      - ./uploads:/home/django/uploads
    
  celery-worker:
    build: ./eduPlatform
    command: celery -A eduPlatform worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - django_network
    env_file:
      - .env.production
    volumes:
      - ./uploads:/home/django/uploads
    
  celery-beat-worker:
    build: ./eduPlatform
    command: celery -A eduPlatform beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - django_network
    env_file:
      - .env.production
    volumes:
      - ./uploads:/home/django/uploads

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - django_network