version: '3.8'

networks:
  django_network:
    driver: bridge

services:
  daphne:
    build: ./eduPlatform
    command: daphne -b 0.0.0.0 -p 8000 eduPlatform.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - django_network
    
  celery-worker:
    build: ./eduPlatform
    command: celery -A eduPlatform worker --loglevel=info
    depends_on:
      - redis
    networks:
      - django_network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - django_network