# Generated by Django 4.2.16 on 2024-11-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meeting', max_length=165)),
                ('session_token', models.CharField(blank=True, max_length=65, unique=True)),
                ('allowed_users', models.ManyToManyField(related_name='conferences', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_conferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
