# Generated by Django 4.2.16 on 2024-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_rename_session_token_conference_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
