# Generated by Django 4.2.16 on 2024-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conference_end_time_conference_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
