# Generated by Django 4.2.16 on 2024-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_conference_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='celery_task_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='max_conference_duration',
            field=models.IntegerField(default=0),
        ),
    ]
