# Generated by Django 4.2.16 on 2024-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_conference_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
