# Generated by Django 4.2.16 on 2024-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_alter_conference_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageCount', models.IntegerField(default=0)),
                ('token', models.CharField(blank=True, default='', max_length=100, unique=True)),
            ],
        ),
    ]
