# Generated by Django 4.2.16 on 2024-12-12 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 23, 2, 39, 815101, tzinfo=datetime.timezone.utc)),
        ),
    ]
