# Generated by Django 4.2.16 on 2024-12-12 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_presentation_time_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='time_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
