# Generated by Django 4.2.16 on 2024-11-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(default="Hi, I'm new around here!", max_length=350, verbose_name='Profile description'),
        ),
    ]
