# Generated by Django 4.2.16 on 2024-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Info_Name', max_length=120)),
                ('description', models.CharField(default='Info_Description', max_length=400)),
            ],
        ),
    ]
